on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: lts/*

      - name: build storybook and deploy
        run: |
          npm install --legacy-peer-deps
          npm run build-storybook

          cd storybook-static
          git init
          git config --local user.name mebtte
          git config --local user.email hi@mebtte.com
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/mebtte/react-lrc.git
          git switch -c gh-pages
          git add -A
          git commit -m "auto deploy"
          git push -f origin gh-pages
