name: build and deploy playgroun on gh-pages
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    name: build and deploy playgroun on gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: use node.js@12.x
        uses: actions/setup-node@main
        with:
          node-version: 12.x

      - name: build react-lrc
        run: |
          npm install
          npm run build

      - name: build playground and deploy on gh-pages
        env:
          TOKEN: ${{secrets.TOKEN}}
          PUBLIC_URL: /react-lrc
        run: |
          cd playground
          npm install
          npm run build -- --public-url /react-lrc
          cd build
          git init
          git config --local user.name mebtte
          git config --local user.email hi@mebtte.com
          git remote add origin https://$TOKEN@github.com/$GITHUB_REPOSITORY.git
          git switch -c gh-pages
          git add -A
          git commit -m "deploy playground"
          git push origin gh-pages -f
